;=============================================================================;
; GLOSS - Generic Loader for Operating SystemS                                ;
; An extensible and configurable bootloader.                                  ;
;-----------------------------------------------------------------------------;
; Copyright (C) 2013-2016 ~ Adrian J. Collado       [acollado@polaritech.com] ;
; Copyright (C) 2015-2016 ~ Polaritech, Inc.         [https://polaritech.com] ;
; All Rights Reserved                                                         ;
;=============================================================================;

%ifndef ASSEMBLYFUNCTIONS_IAPX86_A20_A20INC
%define ASSEMBLYFUNCTIONS_IAPX86_A20_A20INC

; %include "Check.BIOS.inc"
%include "Check.Wrap.inc"
; %include "Disable.inc"
%include "Enable.inc"
%include "Toggle.BIOS.inc"
%include "Toggle.Fast.inc"
%include "Toggle.PS2.inc"
; %include "Toggle.inc"

%endif ;ASSEMBLYFUNCTIONS_IAPX86_A20_A20INC